apiVersion: v1
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.scrapeinterval }}
    scrape_configs:
    - job_name: {{ .Values.prometheus.jobname }}
      static_configs:
      - targets: ['{{ include "csvserver.name" . }}:{{ .Values.csvserver.service.port }}']
kind: ConfigMap
metadata:
  name: {{ include "prometheus.name" . }}
