apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "prometheus.labels" . | indent 4 }}
  name: {{ include "prometheus.name" . }}
spec:
  type: {{ .Values.prometheus.service.type }}
  ports:
  - port: {{ .Values.prometheus.service.port }}
    {{- if $.Values.prometheus.service.targetPorts }}
    targetPort: {{ $.Values.prometheus.service.targetPorts }}
    {{- else }}
    targetPort: ClusterIP
    {{- end }}
    protocol: {{ .Values.prometheus.service.protocol }}
  selector:
    {{- include "prometheus.labels" . | indent 4 }}

